[project]
name = "arctic-sea-ice-data-fusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.14.0",
    "matplotlib>=3.10.3",
    "scipy>=1.15.3",
]
